"""Benizakura: Regression testing and evaluation gating framework for AI behaviors."""

from benizakura.models import (
    BidirectionalEvaluationResult,
    BidirectionalResult,
    ComparisonIdentity,
    ComparisonResult,
    ConsistencyClassification,
    ConsistencyOutcome,
    Criterion,
    CriterionAssessment,
    EvaluationCase,
    EvaluationResult,
    EvaluationRun,
    NormalizedWinner,
    PairwiseJudgment,
    PairwiseWinner,
    RawPositionWinner,
    Rubric,
    StandardCriteria,
    Verdict,
    classify_consistency,
)
from benizakura.runner import EvaluationRunner, Evaluator, MockEvaluator
from benizakura.comparator import Comparator, SimpleComparator
from benizakura.errors import (
    BenizakuraJudgeError,
    JudgeParseError,
    JudgeProviderError,
    JudgeValidationError,
)
from benizakura.judge import (
    JudgePromptBuilder,
    JudgeProvider,
    JudgeRequest,
    JudgeResponse,
    JudgeResponseParser,
    LLMPairwiseJudge,
    MockJudgeProvider,
    MockPairwiseJudge,
    PairwiseJudge,
    PairwiseJudgeCall,
)
from benizakura.pairwise_runner import BidirectionalPairwiseRunner
from benizakura.statistical import (
    CriterionAggregate,
    EffectSize,
    EvaluationDataset,
    EvaluationSample,
    PairedCaseOutcome,
    StatisticalAnalysis,
    StatisticalAnalyzer,
)
from benizakura.gate import (
    GateConfig,
    GateResult,
    ReleaseGate,
)
from benizakura.calibration import (
    AdjudicationRecord,
    AgreementStatistics,
    AnnotatorSubmission,
    ConfusionMatrix,
    GroundTruthArtifact,
    GroundTruthStatus,
    apply_adjudications,
    calculate_human_agreement,
    compute_cohens_kappa,
    freeze_ground_truth_artifact,
    load_annotator_submissions,
    validate_annotator_submission,
    validate_submissions_batch,
)


__all__ = [
    "AdjudicationRecord",
    "AgreementStatistics",
    "AnnotatorSubmission",
    "ConfusionMatrix",
    "GroundTruthArtifact",
    "GroundTruthStatus",
    "apply_adjudications",
    "calculate_human_agreement",
    "compute_cohens_kappa",
    "freeze_ground_truth_artifact",
    "load_annotator_submissions",
    "validate_annotator_submission",
    "validate_submissions_batch",
    "BenizakuraJudgeError",
    "BidirectionalEvaluationResult",
    "BidirectionalResult",
    "ComparisonIdentity",
    "ComparisonResult",
    "ConsistencyClassification",
    "ConsistencyOutcome",
    "Criterion",
    "CriterionAggregate",
    "CriterionAssessment",
    "EffectSize",
    "EvaluationCase",
    "EvaluationDataset",
    "EvaluationResult",
    "EvaluationRun",
    "EvaluationSample",
    "GateConfig",
    "GateResult",
    "JudgeParseError",
    "JudgePromptBuilder",
    "JudgeProvider",
    "JudgeProviderError",
    "JudgeRequest",
    "JudgeResponse",
    "JudgeResponseParser",
    "JudgeValidationError",
    "LLMPairwiseJudge",
    "MockJudgeProvider",
    "NormalizedWinner",
    "PairedCaseOutcome",
    "PairwiseJudgment",
    "PairwiseWinner",
    "RawPositionWinner",
    "ReleaseGate",
    "Rubric",
    "StandardCriteria",
    "StatisticalAnalysis",
    "StatisticalAnalyzer",
    "Verdict",
    "classify_consistency",
    "EvaluationRunner",
    "Evaluator",
    "MockEvaluator",
    "Comparator",
    "SimpleComparator",
    "PairwiseJudge",
    "MockPairwiseJudge",
    "PairwiseJudgeCall",
    "BidirectionalPairwiseRunner",
]


