"""Benizakura: Regression testing and evaluation gating framework for AI behaviors."""

from benizakura.models import (
    BidirectionalEvaluationResult,
    BidirectionalResult,
    ComparisonIdentity,
    ComparisonResult,
    ConsistencyClassification,
    ConsistencyOutcome,
    Criterion,
    CriterionAssessment,
    EvaluationCase,
    EvaluationResult,
    EvaluationRun,
    NormalizedWinner,
    PairwiseJudgment,
    PairwiseWinner,
    RawPositionWinner,
    Rubric,
    StandardCriteria,
    Verdict,
    classify_consistency,
)
from benizakura.runner import EvaluationRunner, Evaluator, MockEvaluator
from benizakura.comparator import Comparator, SimpleComparator
from benizakura.errors import (
    BenizakuraJudgeError,
    JudgeParseError,
    JudgeProviderError,
    JudgeValidationError,
)
from benizakura.judge import (
    JudgePromptBuilder,
    JudgeProvider,
    JudgeRequest,
    JudgeResponse,
    JudgeResponseParser,
    LLMPairwiseJudge,
    MockJudgeProvider,
    MockPairwiseJudge,
    PairwiseJudge,
    PairwiseJudgeCall,
)
from benizakura.pairwise_runner import BidirectionalPairwiseRunner
from benizakura.statistical import (
    CriterionAggregate,
    EffectSize,
    EvaluationDataset,
    EvaluationSample,
    PairedCaseOutcome,
    StatisticalAnalysis,
    StatisticalAnalyzer,
)


__all__ = [
    "BenizakuraJudgeError",
    "BidirectionalEvaluationResult",
    "BidirectionalResult",
    "ComparisonIdentity",
    "ComparisonResult",
    "ConsistencyClassification",
    "ConsistencyOutcome",
    "Criterion",
    "CriterionAggregate",
    "CriterionAssessment",
    "EffectSize",
    "EvaluationCase",
    "EvaluationDataset",
    "EvaluationResult",
    "EvaluationRun",
    "EvaluationSample",
    "JudgeParseError",
    "JudgePromptBuilder",
    "JudgeProvider",
    "JudgeProviderError",
    "JudgeRequest",
    "JudgeResponse",
    "JudgeResponseParser",
    "JudgeValidationError",
    "LLMPairwiseJudge",
    "MockJudgeProvider",
    "NormalizedWinner",
    "PairedCaseOutcome",
    "PairwiseJudgment",
    "PairwiseWinner",
    "RawPositionWinner",
    "Rubric",
    "StandardCriteria",
    "StatisticalAnalysis",
    "StatisticalAnalyzer",
    "Verdict",
    "classify_consistency",
    "EvaluationRunner",
    "Evaluator",
    "MockEvaluator",
    "Comparator",
    "SimpleComparator",
    "PairwiseJudge",
    "MockPairwiseJudge",
    "PairwiseJudgeCall",
    "BidirectionalPairwiseRunner",
]


